version: '3.8'

services:
    nginx:
        image: nginx:${NGINX_VERSION}
        container_name: nginx
        restart: always
        environment:
            - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf
            - HOSTNAME=${HOSTNAME}
            - ENDPOINT=${ENDPOINT}
            - PORT=${PORT}
        volumes:
            - ./etc/nginx:/etc/nginx/templates
            - ./var/log/nginx:/var/log/nginx
            - ./:/var/www/html
        ports:
            - '${PORT}:${PORT}'
        links:
            - php
    php:
        build:
            dockerfile: php-fpm-phalcon.dockerfile
            context: ./etc/docker/
            args:
                - PHP_VERSION=${PHP_VERSION}
                - PSR_VERSION=${PSR_VERSION}
                - COMPOSER_VERSION=${COMPOSER_VERSION}
                - PHALCON_VERSION=${PHALCON_VERSION}
        container_name: php
        restart: always
        environment:
            PHP_IDE_CONFIG: serverName=${HOSTNAME}
        working_dir: /var/www/html
        volumes:
            - ./etc/php:/usr/local/etc/php/conf.d
            - ./:/var/www/html
        extra_hosts:
            - host.docker.internal:host-gateway
        links:
            - mongodb
            - memcached
    mongodb:
        image: mongo:${MONGODB_VERSION}
        container_name: mongodb
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=toor
            - MONGO_INITDB_DATABASE=storage
        volumes:
            - ./etc/mongodb:/docker-entrypoint-initdb.d
            - ./mnt/mongodb:/data/db
        ports:
            - '${MONGODB_PORT}:27017'
    memcached:
        image: memcached:${MEMCACHED_VERSION}
        container_name: memcached
        restart: always
        ports:
            - '${MEMCACHED_PORT}:11211'
