version: '3.8'

services:
    nginx:
        image: nginx:${NGINX_VERSION}
        container_name: nginx
        restart: always
        environment:
            - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf
            - HOSTNAME=${HOSTNAME}
            - ENDPOINT=${ENDPOINT}
            - PORT=${PORT}
        volumes:
            - ./../nginx/:/etc/nginx/templates/
            - ./../../var/log/nginx/:/var/log/nginx/
            - ./../../:/var/www/html/
        ports:
            - '${PORT}:${PORT}'
        links:
            - php
    php:
        build:
            dockerfile: ../docker/php-fpm-phalcon.dockerfile
            context: ../docker/
            args:
                - PHP_VERSION=${PHP_VERSION}
                - PSR_VERSION=${PSR_VERSION}
                - COMPOSER_VERSION=${COMPOSER_VERSION}
                - PHALCON_VERSION=${PHALCON_VERSION}
        container_name: php
        restart: always
        environment:
            - MONGO_USERNAME=${MONGO_USERNAME}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - MONGO_DATABASE=${MONGO_DATABASE}
        working_dir: /var/www/html/
        volumes:
            - ./../php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./../../:/var/www/html/
            - ./../../var/log/php/:/var/log/php/
        links:
            - mongodb
            - memcached
    mongodb:
        image: mongo:${MONGODB_VERSION}
        container_name: mongodb
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_USERNAME=${MONGO_USERNAME}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - MONGO_DATABASE=${MONGO_DATABASE}
        volumes:
            - ./../mongodb/:/docker-entrypoint-initdb.d/
            - ./../../mnt/mongodb/:/data/db/
        ports:
            - '${MONGODB_PORT}:27017'
    memcached:
        image: memcached:${MEMCACHED_VERSION}
        container_name: memcached
        restart: always
        ports:
            - '${MEMCACHED_PORT}:11211'
